// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  grid: dynamic(() => import("./Grid")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  nav_item: dynamic(() => import("./NavItem")),
  quote: dynamic(() => import("./Quote")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  two_images: dynamic(() => import("./TwoImages")),
};
